### ISSUE TITLE
social media

### ISSUE THREAD

**Issue by ghost** [arsium/arsium#1]
Hello, do you have any social media ? so I can contact you, the fact is that I have questions, but I would not like to discuss this on github, so please give me contacts if you don't mind for security reasons

**Comment by arsium** [comment]
> Hello, do you have any social media ? so I can contact you, the fact is that I have questions, but I would not like to discuss this on github, so please give me contacts if you don't mind for security reasons 
> 

Yes I have : discord is arsium#4507 and telegram @Arsium_Coder
